### ISSUE TITLE
Sortidx issue

### ISSUE THREAD

**Issue by skyzedout** [moloch--/hashlookup#4]
Thanks for the release man,
Perhaps do you know why when using "sortidx" with a large file (+2GB) ,i instantly get "Index sort complete" (when in reality it doesn't sorted anything), or "Not a valid index file"? ,
Currently i splitted the original "words.txt" files in smaller ones,but can't understand why i get this issue,and after all i'm not a c++ veteran :)

**Comment by moloch--** [comment]
Yea the sorting code is a bit buggy especially for larger datasets (your particular issue is probably due to malloc failing/not handling large alloc's correctly). However, recently I've actually been working on a similar project with a sorter written in Golang, which can handle much much larger data sets and I'm hoping to release soon. So I don't have a good solution for you in the near term other than to maybe wait for that project to complete and re-purpose it's sorter.

**Comment by moloch--** [comment]
I take that back, there's a hacky version of the Golang sorter that should pretty much just work I've added it to this repo here: https://github.com/moloch--/hashlookup/tree/master/sorter

To compile install Go and run `go build .` from the `sorter` directory. 

__Warning:__ I've not test this code with this repo, there may be bugs

**Comment by imaandrew** [comment]
I've tried the golang sorter and it errors after sorting the last tape. I get this error:

```
Loading tape 767 of 767 ...

Go routines: 6 - Heap: 0.008Gb (Max: 0.017Gb) - Time: 2m21.1587414s
Go routines: 6 - Heap: 0.008Gb (Max: 0.017Gb) - Time: 2m22.9004815s
Go routines: 6 - Heap: 0.008Gb (Max: 0.017Gb) - Time: 2m22.9004815s
Go routines: 6 - Heap: 0.008Gb (Max: 0.017Gb) - Time: 2m22.9004815s
Go routines: 6 - Heap: 0.008Gb (Max: 0.017Gb) - Time: 2m22.9004815s
Sorting, please wait ... ⠸ panic: unexpected EOF

goroutine 1 [running]:
main.(*Index).CreateTape(0xc00007a080, 0x2fe, 0x5556, 0x2)
        C:/Users/andre/Downloads/hashlookup/sorter/sorter.go:364 +0x5b7
main.(*Index).Sort(0xc00007a080)
        C:/Users/andre/Downloads/hashlookup/sorter/sorter.go:279 +0x8e5
main.main()
        C:/Users/andre/Downloads/hashlookup/sorter/sorter.go:611 +0x85b
```

**Comment by moloch--** [comment]
Looks like the digest size is off, like I said this code is from a separate project. Try changing the `digestSize` to 8:

https://github.com/moloch--/hashlookup/blob/master/sorter/sorter.go#L60

**Comment by imaandrew** [comment]
That fixed it. Thanks for the help.
